### ISSUE TITLE
Update koop-provider-marklogic on npm

### ISSUE THREAD

**Issue by jkerr5** [koopjs/koop-provider-marklogic#165]
@rgwozdz we need to push the latest provider to npm. Do you have a process for that in koop?

**Comment by rgwozdz** [comment]
Do you want to publish it under the koopjs NPM org?

**Comment by rgwozdz** [comment]
For most of the koopjs repos, the process is:
1. commit that includes appropriate version bump and Changelog entry.  Commit message should be `:package: <version>`. Replace `<version>` with the new package version.
2.  Do a github release; we use `gh-release` to automate.
3. Publish to NPM

**Comment by jkerr5** [comment]
Yes, we would like to update to package here https://www.npmjs.com/package/@koopjs/provider-marklogic. @dmfenton did the first and only publish of it 2 years ago so we need to get it updated with the current version (1.1.0)

**Comment by rgwozdz** [comment]
Ok, will do. Standby.

**Comment by rgwozdz** [comment]
@jkerr5 - master is still at package [version 1.0.0 ](https://github.com/koopjs/koop-provider-marklogic/blob/master/package.json#L3). It won't be publishable until you bump the version because it will conflict with what is already on NPM. Bump the package version to 1.1.0 and let me know - then I will publish.

**Comment by rgwozdz** [comment]
@jkerr5 I see you bumped the version, thanks.

Sorry, I didn't notice before that the package name is currently `koop-provider-marklogic`, which is different then then published NPM name `@koopjs/provider-marklogic`.  Not sure how that happened.  We should change the package name to `@koopjs/provider-marklogic` for consistency and so that we can publish to the same NPM module.  Happy to do that for you if you like.

**Comment by jkerr5** [comment]
Oh yeah, I didn't notice that either! I'll update it and then I need to fix the tag on our release too so it get the right commit. I'll update when I have that fixed.

**Comment by jkerr5** [comment]
OK, I updated the v1.1.0 tag to the correct commit so hopefully everything is correct now.

**Comment by rgwozdz** [comment]
Having an issue publishing - the package is so large (73 Mb) that our rotating one-time-password (for MFA) changes during the publish, and thus the publish get rejected.  Any way to slim down the repo? Can certain things be left out of the NPM with .npmignore?

**Comment by rgwozdz** [comment]
@jkerr5 - it is the `gradle-4.3.1-bin.zip` file - very big.  Does that need to be pushed to NPM?

**Comment by jkerr5** [comment]
No, that doesn't need to be in the repo. Sorry about that! I'll fix and update the release again :/

**Comment by jkerr5** [comment]
OK, I removed that zip file so it should be better now.

**Comment by rgwozdz** [comment]
Boom!  It's published.

**Comment by jkerr5** [comment]
Thanks!

**Comment by jkerr5** [comment]
Hey @rgwozdz, we have 1.2.0 available now so we need to push this to npm again. Is there a way we can do that or automate it so we don't have to bug you for each release?

**Comment by jkerr5** [comment]
@rgwozdz any thoughts on this?

**Comment by jkerr5** [comment]
Closing this as we will request via a new ticket for the next release.
